sudo: false

language: go

go:
  - 1.6

addons:
  apt:
    packages:
      - socklog

cache:
  apt: true
  directories:
    - /home/travis/runit
    - /home/travis/perl5
    - /home/travis/gopath/bin
    - /home/travis/gopath/pkg/linux_amd64/github.com/axw
    - /home/travis/gopath/pkg/linux_amd64/github.com/mattn
    - /home/travis/gopath/pkg/linux_amd64/github.com/pborman
    - /home/travis/gopath/pkg/linux_amd64/github.com/powerman
    - /home/travis/gopath/pkg/linux_amd64/golang.org
    - /home/travis/gopath/pkg/linux_amd64/gopkg.in
    - /home/travis/gopath/src/github.com/axw
    - /home/travis/gopath/src/github.com/mattn
    - /home/travis/gopath/src/github.com/pborman
    - /home/travis/gopath/src/github.com/powerman
    - /home/travis/gopath/src/golang.org
    - /home/travis/gopath/src/gopkg.in

before_install:
  - if [ ! -x "$HOME/runit/runsv" ]; then mkdir -p "$HOME/runit" && wget http://smarden.org/runit/runit-2.1.1.tar.gz -O /tmp/runit-2.1.1.tar.gz && tar -xzvf /tmp/runit-2.1.1.tar.gz -C "$HOME" && cd "$HOME/admin/runit-2.1.1/src/" && echo 'gcc -s -static' > conf-ld && make && cp $(cat ../package/commands) "$HOME/runit/" && cd -; fi
  - export PATH="$HOME/perl5/bin:$HOME/runit:$PATH"
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm -nq CPAN::Meta
  - cpanm -nq File::Spec
  - cpanm -nq Narada
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - go get -v golang.org/x/tools/cmd/cover
script:
  - ./release -f
  - mkdir _live/ && ln -s ../.release _live/.release && cd _live/
  - narada-install "$(cat ../VERSION)" </dev/null
  - narada-start-services & sleep 1
  - prove -r t/devel/
